[Homework #6] - JS Basic 1 by Stanisław Królikiewicz
qaprosoft/react-laba-international-2 pull request #171
Opened 2023-08-15 09:07 UTC by stkrolikiewicz

2023-08-28 12:57 UTC, solvd-mmelnyk requested changes
Please make sure that you format your code with prettier!
please take a look at my comments and make sure that you are using the correct variable name and meaningful variable names

2023-08-28 12:57 UTC, solvd-mmelnyk commented on homeworks/stanislaw-krolikiewicz/06-js-basics-1/script.js
> +const printArray = (Array) => {
please do not use uppercase first letter for variable name

2023-08-28 12:57 UTC, solvd-mmelnyk commented on homeworks/stanislaw-krolikiewicz/06-js-basics-1/script.js
> +  let middle = parseInt(word.length/2)
please use const if you don't need to change variable

2023-08-28 12:57 UTC, solvd-mmelnyk commented on homeworks/stanislaw-krolikiewicz/06-js-basics-1/script.js
> +const findOdd = (Array) => {
do not use uppercase for first word letter

2023-08-28 12:57 UTC, solvd-mmelnyk commented on homeworks/stanislaw-krolikiewicz/06-js-basics-1/script.js
> +  let C = {row: undefined, col: undefined}, m = {row: undefined, col: undefined}, minMoves, width = 0
please use more meaningful variable name
it is hard to understand what this means

2023-08-28 15:19 UTC, stkrolikiewicz commented on homeworks/stanislaw-krolikiewicz/06-js-basics-1/script.js
> +  let C = {row: undefined, col: undefined}, m = {row: undefined, col: undefined}, minMoves, width = 0
Ok, I've provided changes. Let me know if it is ok.

2023-08-28 15:34 UTC, stkrolikiewicz commented
I've provided the changes.

2023-08-29 17:49 UTC, solvd-mmelnyk approved these changes

2023-08-29 17:49 UTC, merged