[Homework #12] Data structures and algorithms by Antonina Vechorko
qaprosoft/react-laba-international-2 pull request #229
Opened 2023-08-27 08:23 UTC by antoninavechorko

2023-08-28 14:03 UTC, solvd-mmelnyk requested changes
I leave comments! Please take a look!
Could you please try to describe what you did?

2023-08-28 14:03 UTC, solvd-mmelnyk commented on homeworks/antonina-vechorko/12-data-structures-and-algorithms /solution.js
> +      return i;
could you please try to explain why you return index instead of value?

2023-08-28 14:03 UTC, solvd-mmelnyk commented on homeworks/antonina-vechorko/12-data-structures-and-algorithms /solution.js
> +  for (const needle of needleList) {
why do you need for...of cycle here? what purpose of this?

2023-08-29 18:03 UTC, solvd-mmelnyk commented
please do not use spaces in file names

2023-09-01 16:18 UTC, antoninavechorko commented
@solvd-mmelnyk errors fixed, I hope now will be ok, thanks.

2023-09-12 10:27 UTC, solvd-mmelnyk approved these changes
LGTM!

2023-09-12 10:27 UTC, solvd-mmelnyk requested changes
Please remove all spaces from file names

2023-09-12 10:32 UTC, antoninavechorko commented
@fixed

2023-09-12 10:32 UTC, solvd-mmelnyk approved these changes

2023-09-12 10:32 UTC, merged