[Homework #9] - JS Advanced 2 by Anastasia Kladova
qaprosoft/react-laba-international-2 pull request #234
Opened 2023-08-27 18:41 UTC by NastyaKladava

Implement all the functionality except the advanced one.

2023-08-31 21:42 UTC, ababenko-solvd requested changes

2023-08-31 21:42 UTC, ababenko-solvd commented on homeworks/anastasia-kladova/09-js-dvanced-2/script.js
> +class Serializable {
You have changes according to HW5, 9 and 13 in this PR
Please leave changes only according to HW9

separate HW = separate corresponding PR

2023-09-01 17:42 UTC, NastyaKladava commented on homeworks/anastasia-kladova/09-js-dvanced-2/script.js
> +class Serializable {
Sorry. Hope I fixed it. I removed from this PR the changes of HW 13. But can't do it for HW5. I think that maybe I've applied prettier and changes appeared in HW5. Maybe I can delete from this branch HW5 for now and than when you'll approve this PR I can add HW5 that you've approved later?

2023-09-09 09:14 UTC, ababenko-solvd approved these changes

2023-09-09 09:14 UTC, ababenko-solvd commented on homeworks/anastasia-kladova/09-js-dvanced-2/script.js
> +class Serializable {
It is ok now.

2023-09-09 09:14 UTC, ababenko-solvd approved these changes

2023-09-09 09:14 UTC, merged