[Homework #9] - JS Advanced 2 by Rodrigo Collins
qaprosoft/react-laba-international-2 pull request #250
Opened 2023-08-30 11:39 UTC by RodrigoCollins

2023-08-31 21:44 UTC, ababenko-solvd requested changes

2023-08-31 21:44 UTC, ababenko-solvd commented on homeworks/antonina-vechorko/08-js-advanced-1 /index.js
> -// task 1 https://github.com/qaprosoft/react-laba-international-2/blob/main/lectures/08-js-advanced-1/task.md#1-pluck
Why did you remove Antonina Vechorko's HW8?

2023-09-01 01:14 UTC, RodrigoCollins commented on homeworks/antonina-vechorko/08-js-advanced-1 /index.js
> -// task 1 https://github.com/qaprosoft/react-laba-international-2/blob/main/lectures/08-js-advanced-1/task.md#1-pluck
thats the file why i wasnt able to clone the repo, when i want to restore it => unable to create file homeworks/antonina-vechorko/08-js-advanced-1 /index.js , cause of the blank space

2023-09-09 09:08 UTC, ababenko-solvd approved these changes

2023-09-09 09:08 UTC, ababenko-solvd commented on homeworks/rodrigo-collins/09-js-advanced-2/index.js
> +    _serializeData(data, supportedTypes) {
Everything is ok
But instead of using else if so many times in a row use "switch case" construction
Your code will be more graceful and easy-readable

2023-09-09 09:10 UTC, ababenko-solvd approved these changes

2023-09-09 09:10 UTC, merged