[Homework #17] - React Basics by Yuri Pantelei
qaprosoft/react-laba-international-2 pull request #322
Opened 2023-09-19 19:01 UTC by kinfris

Please check my task and say is there something wrong, because I`m not confident that I done all correct :)

2023-09-20 11:18 UTC, VitalikMelnyk requested changes
Hello @kinfris.
I have checked your PR and left some comments.

2023-09-20 11:18 UTC, VitalikMelnyk commented on homeworks/yuri-pantsialei/17-react-basics/index.js
> +function head() {
Please, write your components with capital letter.
1. https://react.dev/learn/your-first-component#step-2-define-the-function.
2. https://react.dev/reference/react/createElement

2023-09-20 11:18 UTC, VitalikMelnyk commented on homeworks/yuri-pantsialei/17-react-basics/index.js
> +const colors = ['red', 'yellow', 'green'];
If you have free time, please do this task with the JSX approach.
It would be helpful for future homework.

2023-09-20 11:18 UTC, VitalikMelnyk commented on homeworks/yuri-pantsialei/17-react-basics/index.js
> +function changeActiveColor() {
Your initial color is yellow.
Change to red color or make the initial state without colors.

2023-09-21 09:44 UTC, VitalikMelnyk requested changes

2023-09-21 09:44 UTC, VitalikMelnyk commented on homeworks/yuri-pantsialei/17-react-basics/app.jsx
> +const colors = ['red', 'yellow', 'green'];
Please, format code.

2023-09-21 10:32 UTC, kinfris commented on homeworks/yuri-pantsialei/17-react-basics/app.jsx
> +const colors = ['red', 'yellow', 'green'];
Sorry, didn`t notice that .jsx file doesn`t format automatically as .js file

2023-09-21 12:55 UTC, VitalikMelnyk approved these changes
Approved.

2023-09-21 12:57 UTC, merged