[Homework #18] - React UI by Ivan Ishchenko
qaprosoft/react-laba-international-2 pull request #346
Opened 2023-09-25 12:43 UTC by ViVse

2023-09-26 10:59 UTC, VitalikMelnyk requested changes
Hello @ViVse!
I have checked your PR and left some comments.

2023-09-26 10:59 UTC, VitalikMelnyk commented on homeworks/ivan-ishchenko/18-react-ui/style.css
> +.avatars {
Please fix styles according to the Figma file.
1. Reduce sizes of images.
2. 5 avatars in row.
3. Refresh all buttons shouldn't be fixed. Fix the mobile screen as well.

![Screenshot 2023-09-26 at 13 51 41](https://github.com/qaprosoft/react-laba-international-2/assets/46888925/b0072951-46f0-4c99-8c4d-dfd0ccaf9b70)

2023-09-27 14:28 UTC, ViVse commented
@VitalikMelnyk, fixed all problems.

2023-09-29 09:04 UTC, VitalikMelnyk approved these changes
Approved.

2023-09-29 09:04 UTC, merged