[Homework #18] - React UI by Usmonbek Rustamov
qaprosoft/react-laba-international-2 pull request #349
Opened 2023-09-25 23:32 UTC by usmonbek-umarbekovich

Hey, I completed the homework.

I haven't done a lof of projects using Typescript before. After the Typescript lesson, I really started to enjoy working with it.
Please, have a look at my homework and tell me if there is any mistakes or bad practices.
Thank you

2023-09-26 10:21 UTC, VitalikMelnyk requested changes
Hello @usmonbek-umarbekovich!
I have checked your PR and left some comments.

2023-09-26 10:21 UTC, VitalikMelnyk commented on homeworks/usmonbek-rustamov/18-react-ui/src/components/AvatarList.tsx
> +            first_name={avatar.first_name}
I recommend writing props with camelCase.
E.g: first_name -> firstName and so on.

2023-09-26 10:21 UTC, VitalikMelnyk commented on homeworks/usmonbek-rustamov/18-react-ui/src/components/AvatarList.tsx
> +  const handleRefreshAllAvatars = async () => {
You need to catch errors. Please review cases when you get errors from the backend and show some feedback for the user without crashing the application.
For example: when I added 20 avatars and then wanted to add 21 avatar I got the error.
![Screenshot 2023-09-26 at 13 13 11](https://github.com/qaprosoft/react-laba-international-2/assets/46888925/cb22536b-7bae-45b6-b95f-ac1afdf51945)

2023-09-26 10:21 UTC, VitalikMelnyk commented on homeworks/usmonbek-rustamov/18-react-ui/src/components/AvatarList.tsx
> +            <div className="loader">
You can move this code to separate components more easily and conveniently by dividing them into small components.

2023-09-26 10:21 UTC, VitalikMelnyk commented on homeworks/usmonbek-rustamov/18-react-ui/src/components/AvatarList.tsx
> +            <button className="btn btn-square" onClick={handleAddAvatar}>
The same here.

2023-09-26 10:21 UTC, VitalikMelnyk commented on homeworks/usmonbek-rustamov/18-react-ui/src/components/AvatarList.tsx
> +      <button className="btn btn-refresh" onClick={handleRefreshAllAvatars}>
The same here.

2023-09-26 15:46 UTC, usmonbek-umarbekovich commented on homeworks/usmonbek-rustamov/18-react-ui/src/components/AvatarList.tsx
> +            first_name={avatar.first_name}
Thank you, I learnt Mapped types because of your recommendation

2023-09-26 15:48 UTC, usmonbek-umarbekovich commented
I handled the errors and show those errors to the user using react-toastify. I also restructured the code, seperated the code to new small components

2023-09-29 09:20 UTC, VitalikMelnyk approved these changes
Approved.

2023-09-29 09:21 UTC, merged