[Homework #18] - React UI by Stanisław Królikiewicz
qaprosoft/react-laba-international-2 pull request #359
Opened 2023-09-29 17:04 UTC by stkrolikiewicz

2023-10-04 06:23 UTC, VitalikMelnyk requested changes
Hello @stkrolikiewicz!
I have checked your PR and left some comments.

2023-10-04 06:23 UTC, VitalikMelnyk commented on homeworks/stanislaw-krolikiewicz/18-react-ui/src/pages/index.tsx
> +import {ReactElement, use, useEffect, useState} from 'react';
Remove `use` as a redundant import.

2023-10-04 06:23 UTC, VitalikMelnyk commented on homeworks/stanislaw-krolikiewicz/18-react-ui/src/pages/index.tsx
> +    fetch('https://tinyfac.es/api/data?limit=1&quality=0')
Create a constants file where you can save all constants.
In this case, you can save the URL as a constant and use it everywhere you need.

2023-10-04 06:23 UTC, VitalikMelnyk commented on homeworks/stanislaw-krolikiewicz/18-react-ui/src/pages/index.tsx
> +export default function Home() {
Please, rewrite all functions with async/await approach.

2023-10-04 06:23 UTC, VitalikMelnyk commented on homeworks/stanislaw-krolikiewicz/18-react-ui/src/pages/index.tsx
> +      <Button onClick={fetchAvatars} className="fixed bottom-[24px] z-50">
Move to a separate component.

2023-10-04 06:23 UTC, VitalikMelnyk commented on homeworks/stanislaw-krolikiewicz/18-react-ui/src/components/Tile/Component.tsx
> +  const fetchAvatar = () => {
Also, rewrite with async/await approach.

2023-10-08 13:42 UTC, stkrolikiewicz commented
@VitalikMelnyk I've provided suggested changes. I also changed the structure a little bit. Everything is described inside commit message.

2023-10-10 08:14 UTC, VitalikMelnyk requested changes

2023-10-10 08:14 UTC, VitalikMelnyk commented on homeworks/stanislaw-krolikiewicz/18-react-ui/src/views/Main/Component.tsx
> +export default function Main() {
Please use one approach with promises. 
I recommend using everything in one async/await approach and not combining async/await with then/catch.

2023-10-12 14:50 UTC, VitalikMelnyk approved these changes
Approved.

2023-10-12 14:50 UTC, merged