[Homework #17] - React Basics by Anastasia Kladova
qaprosoft/react-laba-international-2 pull request #364
Opened 2023-10-01 14:23 UTC by NastyaKladava

Implemented the traffic light.

2023-10-02 19:19 UTC, ababenko-solvd requested changes

2023-10-02 19:19 UTC, ababenko-solvd commented on homeworks/anastasia-kladova/17-react-basics/index.jsx
> +  const trafficStates = {
Nice job!
but it is not the best solution - to relate every state with a reference to another state. It is very complex and there is no need to do it. try to find another - more simple and graceful solution.

2023-10-03 18:12 UTC, NastyaKladava commented on homeworks/anastasia-kladova/17-react-basics/index.jsx
> +            style={{
Actually, it was the first thing that came to my mind. But I changed my functionality (use classes) as you advice.

2023-10-06 18:36 UTC, NastyaKladava commented on homeworks/anastasia-kladova/17-react-basics/index.jsx
> +  const trafficStates = {
I changed my solution. Please, check.

2023-10-11 04:40 UTC, ababenko-solvd approved these changes

2023-10-11 04:40 UTC, merged