[Homework #19] - React Hooks by Rodrigo Collins
qaprosoft/react-laba-international-2 pull request #373
Opened 2023-10-03 21:15 UTC by RodrigoCollins

2023-10-04 17:36 UTC, ababenko-solvd requested changes

2023-10-04 17:36 UTC, ababenko-solvd commented on homeworks/rodrigo-collins/19-react-hooks/src/App.tsx
> +      alert('To-Do already exists');
This error goes also if you save todo with the same text - but it should not

2023-10-04 17:36 UTC, ababenko-solvd commented on homeworks/rodrigo-collins/19-react-hooks/src/App.tsx
> +    if (!validateTodoText(trimmedTask)) {
Hint:
you can write 1-line conditions in such way - will look better and shorter:

if (!validateTodoText(trimmedTask)) return;

2023-10-04 17:36 UTC, ababenko-solvd commented on homeworks/rodrigo-collins/19-react-hooks/src/components/CreateTodoInput.tsx
> +            placeholder="Create Todo-Task"
Placeholder should not be shown, when the input is focused

2023-10-04 17:36 UTC, ababenko-solvd commented on homeworks/rodrigo-collins/19-react-hooks/src/components/TodoItem.tsx
> +interface Todo {
I see nice progress with types!
Have some more advices.

1) "interface"  is for types inheritance and extending.
For simple types use "type"
type Todo = {
    id: number;
    text: string;
    completed: boolean;
}

2) Here you have usage of the same types in different components and you are redeclaring them again - this is wrong!
- declare them once(in component or in separate file with types) with export
- import that type to another component(s) and use

then if there would be type changes (they frequently appear) - you will update type in one place

2023-10-04 17:45 UTC, ababenko-solvd requested changes

2023-10-04 17:45 UTC, ababenko-solvd commented on homeworks/rodrigo-collins/19-react-hooks/src/components/TodoList.tsx
> +export default TodoList;
Complementary tasks for you, if you have time and motivation:

1) Add ability to add new todo not only by clicking the btn, but also by pressing "Enter"
2) Stop using Alerts for errors - add some UI based solution

2023-10-17 15:56 UTC, RodrigoCollins commented on homeworks/rodrigo-collins/19-react-hooks/src/components/TodoItem.tsx
> +interface Todo {
Done!

2023-10-17 16:01 UTC, RodrigoCollins commented on homeworks/rodrigo-collins/19-react-hooks/src/App.tsx
> +    if (!validateTodoText(trimmedTask)) {
done

2023-10-17 16:28 UTC, RodrigoCollins commented on homeworks/rodrigo-collins/19-react-hooks/src/components/CreateTodoInput.tsx
> +            placeholder="Create Todo-Task"
done

2023-10-17 18:52 UTC, ababenko-solvd approved these changes

2023-10-17 18:52 UTC, merged