[Homework #18] - React UI by Anastasia Kladava
qaprosoft/react-laba-international-2 pull request #378
Opened 2023-10-05 21:07 UTC by NastyaKladava

Implement all the needed functionality.

2023-10-06 09:59 UTC, ababenko-solvd requested changes

2023-10-06 09:59 UTC, ababenko-solvd commented on homeworks/anastasia-kladova/18-react-ui/src/App.js
> +    setAvatars([...data]);
Here is no need to do destructuring, because there is no need to copy an object. You simply fetch the data and place it to State.
setAvatars(data)

2023-10-06 09:59 UTC, ababenko-solvd commented on homeworks/anastasia-kladova/18-react-ui/src/App.js
> +import './index.css';
Really good job!
I just want you to do couples of addons, that is necessary in real project.

1) Add state called 'loading', which is false by default, set to true, when you are fetching data from server and go back to false, when data is fetched. While loading === true, buttons are disabled.
It is great to add loaders for every single avatar and disable it's refresh btn separately. think how to do it better - if you have any questions - feel free to ask me in our channel.
2) Cursor should be changed cursor to "pointer" for clickable elements. Also make sinhgle ava refresh icon-button responsive to click (you can rotate it, change color, when ava loading starts and retur prev visual state, when it is finished)
3) Don't forget to add responsiveness for all screens (mobile => => => desktop) - it is very simple to do with flex positioning.

2023-10-07 17:01 UTC, NastyaKladava commented on homeworks/anastasia-kladova/18-react-ui/src/App.js
> +import './index.css';
I made advised addons. If something is wrong, please, let me know)

2023-10-11 06:48 UTC, ababenko-solvd approved these changes

2023-10-11 06:48 UTC, ababenko-solvd commented on homeworks/anastasia-kladova/18-react-ui/src/App.js
> +    setAvatars([data]);
Data comes as Array already
 setAvatars(data);

2023-10-11 06:49 UTC, merged