[Homework #19] - React Hooks by Ivan Ishchenko
qaprosoft/react-laba-international-2 pull request #381
Opened 2023-10-08 12:07 UTC by ViVse

2023-10-09 08:40 UTC, VitalikMelnyk requested changes
Hello @ViVse!
I have checked your PR and left some comments.

2023-10-09 08:40 UTC, VitalikMelnyk commented on homeworks/ivan-ishchenko/19-react-hooks/src/components/Input.js
> +  let props = {};
What is the goal of these two lines of code?
When you want to pass ref from parent to child, you need to use forwardRef.
https://react.dev/reference/react/forwardRef

2023-10-09 08:40 UTC, VitalikMelnyk commented on homeworks/ivan-ishchenko/19-react-hooks/src/App.js
> +    if (newTask.trim().length === 0) {
Add validation for maximum input characters (for example 40).

2023-10-09 09:25 UTC, ViVse commented
@VitalikMelnyk, fixed all problems

2023-10-10 08:08 UTC, VitalikMelnyk approved these changes
Approved.

2023-10-10 08:09 UTC, merged