[Homework #19] - React Hooks by Stanisław Królikiewicz
qaprosoft/react-laba-international-2 pull request #382
Opened 2023-10-09 11:35 UTC by stkrolikiewicz

2023-10-16 08:33 UTC, VitalikMelnyk requested changes
Hello @stkrolikiewicz!
I have checked your PR and left some comments.

2023-10-16 08:33 UTC, VitalikMelnyk commented on homeworks/stanislaw-krolikiewicz/19-react-hooks/src/pages/index.tsx
> +export default function Home() {
Fix responsive design.
![Screenshot 2023-10-16 at 11 29 19](https://github.com/qaprosoft/react-laba-international-2/assets/46888925/47956d8c-1475-4ac4-8a7a-6f43058bb96b)

2023-10-16 08:33 UTC, VitalikMelnyk commented on homeworks/stanislaw-krolikiewicz/19-react-hooks/src/components/Task/Component.tsx
> +  const handleUpdate = () => {
Fix edit functionality. When I click edit button, I have got an error with "Task already exists"
![Screenshot 2023-10-16 at 11 29 01](https://github.com/qaprosoft/react-laba-international-2/assets/46888925/683f7f70-1772-43fe-b547-a3ac499a759f)

2023-10-17 08:45 UTC, stkrolikiewicz commented on homeworks/stanislaw-krolikiewicz/19-react-hooks/src/pages/index.tsx
> +export default function Home() {
@VitalikMelnyk I've provided the changes.

2023-10-17 12:26 UTC, VitalikMelnyk approved these changes
Approved.

2023-10-17 12:26 UTC, merged