[Homework #20] - React API by Stanisław Królikiewicz
qaprosoft/react-laba-international-2 pull request #393
Opened 2023-10-11 11:10 UTC by stkrolikiewicz

2023-10-16 09:36 UTC, VitalikMelnyk requested changes
Hello @stkrolikiewicz 
I have checked your PR and left comment.

2023-10-17 09:36 UTC, stkrolikiewicz commented on homeworks/stanislaw-krolikiewicz/20-react-api/src/pages/index.tsx
> +export default function Home() {
Hi @VitalikMelnyk ! I have provided changes that you requested. I hope it solves the problem.

2023-10-17 12:28 UTC, VitalikMelnyk approved these changes

2023-10-17 12:28 UTC, VitalikMelnyk commented
Approved.

2023-10-17 12:28 UTC, merged