[Homework #23] - Testing by Andrew Kondratiyk
qaprosoft/react-laba-international-2 pull request #402
Opened 2023-10-14 21:07 UTC by Gandrejko

2023-10-16 23:06 UTC, ababenko-solvd requested changes

2023-10-16 23:06 UTC, ababenko-solvd commented on homeworks/andrew-kondratiyk/23-testing/src/components/common/todo-card/TodoCard.test.tsx
> +    userEvent.click(editButton);
Did you try "npm run test"? 2 tests are failed.

UserEvent needs await:

it('renders EditTodoCard when isEdit is true', async () => {
    renderWithClient(<TodoCard todo={mockTodo} />);

    const editButton = screen.getByText('Edit');
    await userEvent.click(editButton);

    const editTodoCard = screen.getByTestId('edit-todo-card');

    expect(editTodoCard).toBeInTheDocument();
  });

The same for 'calls onCancel callback when cancel button is clicked' in "EditTodoCard.test.tsx"

2023-10-17 18:17 UTC, Gandrejko commented on homeworks/andrew-kondratiyk/23-testing/src/components/common/todo-card/TodoCard.test.tsx
> +    userEvent.click(editButton);
Anyway, tests are written to be failed)

2023-10-17 19:01 UTC, ababenko-solvd approved these changes

2023-10-17 19:03 UTC, merged