[Homework #23] - Testing by Ivan Ishchenko
qaprosoft/react-laba-international-2 pull request #413
Opened 2023-10-19 13:45 UTC by ViVse

2023-10-19 14:10 UTC, VitalikMelnyk requested changes
Hello @ViVse!
Please add tests for other components, not only for App.js.
E.g: for Input.js, Task.js.

2023-10-19 14:40 UTC, ViVse commented
@VitalikMelnyk, added more tests

2023-10-19 14:53 UTC, VitalikMelnyk requested changes
Hello @ViVse!
I have checked your PR and left comments.

2023-10-19 14:53 UTC, VitalikMelnyk commented on homeworks/ivan-ishchenko/23-testing/src/components/Input.test.js
> +    render(<Input />);
Please fix this console error.
<img width="1434" alt="Screenshot 2023-10-19 at 17 49 00" src="https://github.com/qaprosoft/react-laba-international-2/assets/46888925/d1869eb0-b514-4795-8855-be797dfed2fb">

2023-10-19 14:53 UTC, VitalikMelnyk commented on homeworks/ivan-ishchenko/23-testing/src/components/Task.test.js
> +import React from 'react';
Please, fix this error in console.
<img width="1470" alt="Screenshot 2023-10-19 at 17 50 52" src="https://github.com/qaprosoft/react-laba-international-2/assets/46888925/0b018c60-b111-4970-8cc7-1b037851f6c7">

2023-10-20 09:26 UTC, ViVse commented
@VitalikMelnyk, fixed errors

2023-10-20 12:11 UTC, VitalikMelnyk approved these changes
Approved.

2023-10-20 12:11 UTC, merged