[Homework #5] - CSS-Advanced by Usmonbek Rustamov
qaprosoft/react-laba-international-2 pull request #84
Opened 2023-07-17 19:47 UTC by usmonbek-umarbekovich

Hello,

I have implemented the website. It is responsive and has some nice animation.
Let me know what you think, thank you

2023-07-19 13:06 UTC, VitalikMelnyk requested changes
I have checked your PR.
Just need to fix one issue with icons.

2023-07-19 13:06 UTC, VitalikMelnyk commented on homeworks/usmonbek-rustamov/05-css-advanced/index.html
> +            <use href="./assets/icons/sun.svg#sun"></use>
Please, fix icons.
![Screenshot 2023-07-19 at 16 05 04](https://github.com/qaprosoft/react-laba-international-2/assets/46888925/4617115b-9659-461c-9370-dcaaae0222c8)
![Screenshot 2023-07-19 at 16 05 00](https://github.com/qaprosoft/react-laba-international-2/assets/46888925/b99f1a2e-8d7f-48de-b228-b15d6ebe04a5)

2023-07-19 16:18 UTC, usmonbek-umarbekovich commented on homeworks/usmonbek-rustamov/05-css-advanced/index.html
> +            <use href="./assets/icons/sun.svg#sun"></use>
I checked it on many browsers and the icons are showing.  Can you tell me which browser did you use?

2023-07-19 17:05 UTC, usmonbek-umarbekovich commented
I think that should fix the issue if you're using older version of the browser. Please let me know if it works for you now

2023-07-20 15:40 UTC, VitalikMelnyk commented on homeworks/usmonbek-rustamov/05-css-advanced/index.html
> +            <use href="./assets/icons/sun.svg#sun"></use>
Not working in Safari and Chrome.

2023-07-20 15:40 UTC, VitalikMelnyk commented
@usmonbek-umarbekovich, the same issue with icons.
I have the latest version of Chrome.
Maybe, replace a logic with the `use` tag to something else because the same problem occurred.

2023-07-20 16:34 UTC, usmonbek-umarbekovich commented
I changed use to img. Now it should work

2023-07-21 09:42 UTC, VitalikMelnyk approved these changes

2023-07-21 09:43 UTC, VitalikMelnyk commented
Well Done @usmonbek-umarbekovich!
Approved.

2023-07-21 09:43 UTC, merged